import java.sql.*;
import Project.ConnectionProvider;
import com.itextpdf.text.Chunk;
import com.itextpdf.text.pdf.PdfPTable;
import javax.swing.JOptionPane;
import java.text.SimpleDateFormat;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.Date;
import javax.swing.table.DefaultTableModel;
import java.io.FileOutputStream;
import com.itextpdf.text.Font;
import com.itextpdf.text.Document;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfWriter;
import com.itextpdf.text.Image;
import com.itextpdf.text.FontFactory;
import com.itextpdf.text.Element;
import com.itextpdf.text.Phrase;
import java.io.File;



/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author asus
 */
public class billing extends javax.swing.JFrame {
    public int finalTotal=0;

    /**
     * Creates new form billing
     */
    public billing() {
        initComponents();
        SimpleDateFormat dFormat=new SimpleDateFormat("dd-MM-yyyy");
        Date date= new Date();
        jLabel5.setText(dFormat.format(date));
        
        DateTimeFormatter dtf=DateTimeFormatter.ofPattern("HH:mm:ss:a");
        LocalDateTime now=LocalDateTime.now();
        jLabel6.setText(dtf.format(now));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jTextField10 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        jTextField12 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(100, 150));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/billing frame.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 18, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Billing ani.gif"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(87, 0, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Date:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(924, 15, 41, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Time:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(924, 60, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("jLabel5");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(983, 15, 96, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("jLabel6");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(983, 60, 96, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 114, 1152, 13));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("Buyer Details:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 133, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Name");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 170, 51, -1));

        jTextField1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(88, 167, 180, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Contact Number");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(286, 170, -1, -1));

        jTextField2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(422, 167, 140, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("Email");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 170, 48, -1));

        jTextField3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(646, 167, 220, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("Address");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(884, 170, -1, -1));

        jTextField4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(959, 167, 180, -1));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 208, 1152, 10));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel12.setText("Product Details:");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 230, -1, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setText("Product ID");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 267, -1, -1));

        jTextField5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(115, 264, 55, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setText("Product Name");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(188, 267, -1, -1));

        jTextField6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(309, 264, 167, -1));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setText("Rate");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(494, 267, -1, -1));

        jTextField7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(546, 264, 81, -1));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel16.setText("Quantity");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(645, 267, -1, -1));

        jTextField8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(725, 264, 60, -1));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel17.setText("Description");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(807, 267, -1, -1));

        jTextField9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(907, 264, 234, -1));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/add.png"))); // NOI18N
        jButton1.setText("Add");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 299, -1, -1));
        getContentPane().add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 337, 1152, 10));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "pId", "Name", "Description", "Rate", "Quantity", "sub Total"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 353, 597, 191));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel18.setText("Calculation Details");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(627, 361, -1, -1));

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel19.setText("Total");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(627, 421, 48, -1));

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel20.setText("Paid Amount");
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(627, 465, -1, -1));

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel21.setText("Return Amount");
        getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(627, 505, -1, -1));

        jTextField10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(jTextField10, new org.netbeans.lib.awtextra.AbsoluteConstraints(756, 414, 216, -1));

        jTextField11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextField11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField11ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField11, new org.netbeans.lib.awtextra.AbsoluteConstraints(756, 458, 216, -1));

        jTextField12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(jTextField12, new org.netbeans.lib.awtextra.AbsoluteConstraints(756, 502, 216, -1));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/save.png"))); // NOI18N
        jButton2.setText("Save");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1018, 412, 95, -1));

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Reset.png"))); // NOI18N
        jButton3.setText("Reset");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1018, 456, -1, -1));

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/close Jframe.png"))); // NOI18N
        jButton4.setText("Close");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1018, 500, 95, -1));

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/billing background.png"))); // NOI18N
        getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
        String name= jTextField1.getText();
        try
        {
            Connection con= ConnectionProvider.getCon();
            Statement st= con.createStatement();
            ResultSet rs= st.executeQuery("select *from buyer where name like '"+name+"%'");
            if(rs.next())
            {
                jTextField1.setText(rs.getString(1));
                jTextField2.setText(rs.getString(2));
                jTextField3.setText(rs.getString(3));
                jTextField4.setText(rs.getString(4));
            }
            else
            {
                jTextField2.setText("");
                jTextField3.setText("");
                jTextField4.setText("");
            }
        }    
            catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        
        }
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
        String contactNo= jTextField2.getText();
        try
        {
            Connection con= ConnectionProvider.getCon();
            Statement st= con.createStatement();
            ResultSet rs= st.executeQuery("select *from buyer where contactNo like '"+contactNo+"%'");
            if(rs.next())
            {
                jTextField1.setText(rs.getString(1));
                jTextField2.setText(rs.getString(2));
                jTextField3.setText(rs.getString(3));
                jTextField4.setText(rs.getString(4));
            }
            else
            {
                jTextField1.setText("");
                jTextField3.setText("");
                jTextField4.setText("");
            }
        }    
            catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        
        }
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
        String pId= jTextField5.getText();
        try
        {
            Connection con= ConnectionProvider.getCon();
            Statement st= con.createStatement();
            ResultSet rs= st.executeQuery("select *from product where pId like '"+pId+"%'");
            if(rs.next())
            {
                jTextField6.setText(rs.getString(2));
                jTextField7.setText(rs.getString(3));
                jTextField8.setText(("1"));
                jTextField9.setText(rs.getString(4));
            }
            else
            {
                jTextField6.setText("");
                jTextField7.setText("");
                jTextField8.setText("");
                jTextField9.setText("");
            }
        }    
            catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try {
        // Get the unit price and quantity from text fields
        int price = Integer.parseInt(jTextField7.getText());
        int quantity = Integer.parseInt(jTextField8.getText());
        
        // Calculate total price
        int total = price * quantity;
        
        // Get the DefaultTableModel from jTable2
        DefaultTableModel model = (DefaultTableModel) jTable2.getModel();
        
        // Add a new row to the table model
        model.addRow(new Object[] {
            jTextField5.getText(),    // column 1: cotent of jTextField5
            jTextField6.getText(),    // Column 2: Content of jTextField6
            jTextField9.getText(),    // Column 3: Content of jTextField9
            price,                    // Column 4: Price (as Object)
            quantity,                 // Column 5: Quantity (as Object)
            total                     // Column 6: Total (as Object)
        }); 
        
        // Update the finalTotal
        finalTotal += total;
        
        // Update jTextField10 with the new final total
        jTextField10.setText(String.valueOf(finalTotal));
        jTextField10.setEditable(false);
        
       } 
       catch (NumberFormatException e) 
       {
        // Handle invalid input (non-integer values in text fields)
        JOptionPane.showMessageDialog(this, "Invalid input. Please enter valid numbers.", "Error", JOptionPane.ERROR_MESSAGE);
       }

        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField11ActionPerformed
        // TODO add your handling code here:
       try {
        // Get the paid amount from jTextField11
        String paidAmountStr = jTextField11.getText();
        int paidAmount = Integer.parseInt(paidAmountStr);
        
        // Calculate return amount
        int returnAmount = paidAmount - finalTotal;
        
        // Update jTextField12 with the return amount
        jTextField12.setText(String.valueOf(returnAmount));
        jTextField12.setEditable(false); // Optionally disable editing of return amount field
        } 
       catch (NumberFormatException e) {
        // Handle invalid input (non-integer paid amount)
        JOptionPane.showMessageDialog(this, "Invalid paid amount. Please enter a valid number.", "Error", JOptionPane.ERROR_MESSAGE);
       }

    }//GEN-LAST:event_jTextField11ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new billing().setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    //String pId = jTextField5.getText();
    String name = jTextField1.getText();
    String contactNo = jTextField2.getText();
    String email = jTextField3.getText();
    String address = jTextField4.getText();
    String date = jLabel5.getText();
    String time = jLabel6.getText();// Assuming jLabel5 contains date and jLabel6 contains time
    String total= jTextField10.getText();
    String paidAmount= jTextField11.getText();
    String returnAmount= jTextField12.getText();
    
    // Use current working directory
        String currentDirectory = System.getProperty("user.dir");

        String path = currentDirectory + File.separator + "Invoices" + File.separator;
        
        // Ensure the directory exists
        File invoiceDir = new File(path);
        if (!invoiceDir.exists()) {
            invoiceDir.mkdirs();
        }

    Document doc = new Document();

    try {
        String fileName = name + " " + date + ".pdf";
            String filePath = path + fileName;
            PdfWriter.getInstance(doc, new FileOutputStream(filePath));

        doc.open();
        
        // Add logo to the top center
        Image logo = Image.getInstance("F:\\Urbanmarket.png"); // Set the path to your logo image
        logo.setAlignment(Image.ALIGN_CENTER);
        logo.scaleToFit(100, 100); // Resize the logo if needed
        doc.add((Element) logo);
        
       
        // Title and contact info
        Paragraph title = new Paragraph();
        title.add(new Phrase("Urban Market\n", FontFactory.getFont(FontFactory.HELVETICA_BOLD, 12)));
        title.add("Shaheb Bazar\n");
        title.add("Rajshai, Bangladesh\n");
        title.add("Contact No: +880 1798798780\n");
        doc.add(title);

        // buyer details
        Paragraph buyerDetails = new Paragraph();
        buyerDetails.setAlignment(Element.ALIGN_LEFT); // Set alignment to left for buyer details;
        //buyerDetails.add("Buyer Details:\n");
        buyerDetails.add(new Chunk("Buyer Details: \n", FontFactory.getFont(FontFactory.HELVETICA, 12, Font.BOLD)));
        buyerDetails.add("Name: " + name + "\n");
        buyerDetails.add("Contact No: " + contactNo + "\n");
        buyerDetails.add("Email: " + email + "\n");
        buyerDetails.add("Address: " + address + "\n\n");
        
        
        // Add Date & Time at the top right corner
        Chunk dateAndTimeChunk = new Chunk("Date & Time: " + date + "  " + time);
        Paragraph dateAndTime = new Paragraph(dateAndTimeChunk);
        dateAndTime.setAlignment(Element.ALIGN_RIGHT); // Align to the right
        doc.add(dateAndTime);
        doc.add(buyerDetails);

        // Table for items
        PdfPTable table = new PdfPTable(6);
        table.addCell("pId");
        table.addCell("Name");
        table.addCell("Description");
        table.addCell("Rate");
        table.addCell("Quantity");
        table.addCell("Sub total");

        // Populate table with data from jTable2
        for (int i = 0; i < jTable2.getRowCount(); i++) {
            String pi = jTable2.getValueAt(i,0).toString();
            String n = jTable2.getValueAt(i, 1).toString();
            String d = jTable2.getValueAt(i, 2).toString();
            String r = jTable2.getValueAt(i, 3).toString();
            String q = jTable2.getValueAt(i, 4).toString();
            String s = jTable2.getValueAt(i, 5).toString();
            
            table.addCell(pi);
            table.addCell(n);
            table.addCell(d);
            table.addCell(r);
            table.addCell(q);
            table.addCell(s);
        }

        doc.add(table);
        
        
        

        // Total, paid amount, return amount, and closing message
Paragraph summary = new Paragraph();
summary.setAlignment(Element.ALIGN_LEFT); // Align text to the left

// Add content line by line using Chunk objects
summary.add(new Chunk("\nTotal: ", FontFactory.getFont(FontFactory.HELVETICA, 11, Font.BOLD)));
summary.add(jTextField10.getText() + "\n");

summary.add(new Chunk("Paid Amount: ", FontFactory.getFont(FontFactory.HELVETICA, 11, Font.BOLD)));
summary.add(jTextField11.getText() + "\n");

summary.add(new Chunk("Return Amount: ", FontFactory.getFont(FontFactory.HELVETICA, 11, Font.BOLD)));
summary.add(jTextField12.getText() + "\n");

summary.add("\n\nReceived by _______________                                            Issued by _______________\n");

summary.add(new Chunk("\nTurms & Conditions: \n", FontFactory.getFont(FontFactory.HELVETICA, 11, Font.BOLD)));
summary.add("1. Goods once sold will not be refunded & changed.\n");
summary.add("2. The products under warranty will be repaired or replaced by the manufacturer company.\n");
summary.add("3. Timing for the warranty process will be controlled by the manufucturing company. \n");
summary.add("4. For standard Terms of warranty in detail please visit- urbanmarket.com/page/warranty \n\n");



summary.add("\nThank you for visiting! Please come again.\n");

// Add the styled summary paragraph to the document
doc.add(summary);

// Establish database connection and prepare statements
        Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/bms", "root", "");
        con.setAutoCommit(false);

        // Insert billing details into billing table
        String billingQuery = "INSERT INTO billing (buyerName, contactNo, email, address, date, time, total, paidAmount, returnAmount, pdfPath) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";
        PreparedStatement pstBilling = con.prepareStatement(billingQuery, PreparedStatement.RETURN_GENERATED_KEYS);
        pstBilling.setString(1, name);
        pstBilling.setString(2, contactNo);
        pstBilling.setString(3, email);
        pstBilling.setString(4, address);
        pstBilling.setString(5, date);
        pstBilling.setString(6, time);
        pstBilling.setString(7, total);
        pstBilling.setString(8, paidAmount);
        pstBilling.setString(9, returnAmount);
        pstBilling.setString(10, filePath); // Store the absolute path of the PDF
        pstBilling.executeUpdate();

        // Retrieve the generated billNo
        ResultSet rs = pstBilling.getGeneratedKeys();
        rs.next();
        int billNo = rs.getInt(1);
        
        // Add Invoice Number to PDF
        Paragraph invoiceNumber = new Paragraph("Invoice Number: " + billNo, FontFactory.getFont(FontFactory.HELVETICA_BOLD, 12));
        invoiceNumber.setAlignment(Element.ALIGN_RIGHT);
        doc.add(invoiceNumber);

        // Insert product details into billing_products table
        String productQuery = "INSERT INTO billing_products (billNo, pId, pName, description, rate, quantity, subtotal) VALUES (?, ?, ?, ?, ?, ?, ?)";
        PreparedStatement pstBillingProducts = con.prepareStatement(productQuery);

        for (int i = 0; i < jTable2.getRowCount(); i++) {
            String pId = jTable2.getValueAt(i, 0).toString();
            String pName = jTable2.getValueAt(i, 1).toString();
            String description = jTable2.getValueAt(i, 2).toString();
            String rate = jTable2.getValueAt(i, 3).toString();
            String quantity = jTable2.getValueAt(i, 4).toString();
            String subtotal = jTable2.getValueAt(i, 5).toString();

            table.addCell(pId);
            table.addCell(pName);
            table.addCell(description);
            table.addCell(rate);
            table.addCell(quantity);
            table.addCell(subtotal);

            pstBillingProducts.setInt(1, billNo);
            pstBillingProducts.setString(2, pId);
            pstBillingProducts.setString(3, pName);
            pstBillingProducts.setString(4, description);
            pstBillingProducts.setString(5, rate);
            pstBillingProducts.setString(6, quantity);
            pstBillingProducts.setString(7, subtotal);
            pstBillingProducts.addBatch();
        }

        pstBillingProducts.executeBatch();
        con.commit();

       // doc.add(table);


        JOptionPane.showMessageDialog(null, "Bill Generated");
        // Clear text fields after generating the bill
        //this.dispose();
        // Open a new billing window
        billing newBillingWindow = new billing();
        newBillingWindow.setVisible(true);
        
        // Close the current window (JFrame)
        this.dispose(); // Close the billing window after generating the bill

    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Error generating bill: " + e.getMessage());
        e.printStackTrace(); // Print stack trace for debugging
    } finally {
        if (doc != null) {
            doc.close(); // Ensure the document is properly closed
        }
    } 

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
        String pName= jTextField6.getText();
        try
        {
            Connection con= ConnectionProvider.getCon();
            Statement st= con.createStatement();
            ResultSet rs= st.executeQuery("select *from product where pName like '"+pName+"%'");
            if(rs.next())
            {
                jTextField5.setText(rs.getString(1));
                jTextField6.setText(rs.getString(2 ));
                jTextField7.setText(rs.getString(3));
                jTextField8.setText(("1"));
                jTextField9.setText(rs.getString(4));
            }
            else
            {
                jTextField5.setText("");
                jTextField7.setText("");
                jTextField8.setText("");
                jTextField9.setText("");
            }
        }    
            catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jTextField6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(billing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(billing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(billing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(billing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new billing().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
